#! /bin/bash

print_usage(){
>&2 cat <<EOF
$0 -c <control bam file> -t <tumor bam file> -i <genome index> -b <centromere bed file> -w <exome whitelist> -s <scratch output>
	Wrapper script for Varscan2
	Runs the following steps:
	1. samtools flagstat on each bam file
	2. samtools mpileup on both bam files
	3. determine unique mapped read ratio
	4. VarScan copynumber
	5. Remove low coverage regions
	6. VarScan copyCaller
	7. calculate median for recentering
	8. VarScan copyCaller recenter
	9. Separate chromosome arms
	10. DNAcopy
	11. Merge chromosome arms

OPTIONS:
   -h      Show this message
   -t      tumor bam file
   -c      control bam file
   -i      path to samtools genome index
   -b      centromere locations (bed format)
   -w      exome whitelist (bed format)
   -s      directory for temporary files
   -n      <varscan.N> instead of creating a new temporary directory, use this one

IMPORTANT NOTE: this script expects a copy of VarScan.jar in the same directory as this program. For details on downloading Varscan, see the README

EOF
}

cBam=
tBam=
idx=
cent=
white=
scratch=
prevDir=

while getopts "ht:c:i:b:w:s:n:a:d" OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         t)
             tBam=$OPTARG
             ;;
         c)
             cBam=$OPTARG
             ;;
         i)
             idx=$OPTARG
             ;;
         b)
             cent=$OPTARG
             ;;
         w)
             white=$OPTARG
             ;;
         s)
             scratch=$OPTARG
             ;;
         d)
             DEBUG=1
             ;;
         n)
             prevDir=$OPTARG
             ;;
         ?)
             print_usage
             exit
             ;;
     esac
done


if [[ -z $cBam ]] || [[ -z $tBam ]] || [[ -z $idx ]] || [[ -z $cent ]] || [[ -z $white ]]
then
     print_usage
     >&2 echo "ERROR: Can't find all input files"
     exit 1
fi

graceful_death() {
	>&2 echo "ERROR: Cannot finish $0 because $1";
	exit 1
}

if [ ! -e "$cBam" ]; then
	graceful_death "cannot find control bam file $cBam"
fi 
if [ ! -e "$tBam" ]; then
	graceful_death "cannot find tumor bam file $tBam"
fi 
if [ ! -e "$idx" ]; then
	graceful_death "cannot find samtools index $idx"
fi 
if [ ! -e "$cent" ]; then
	graceful_death "cannot find centromere bed file $cent"
fi 
if [ ! -e "$white" ]; then
	graceful_death "cannot find exome whitelist $white"
fi 

tmpdir=
if [[ -z "$prevDir" ]] && [[ -z $scratch ]]; then
	graceful_death "Please give either the -n OR -s option"
fi

# select correct temp dir
if  [[ -z "$prevDir" ]]; then
	if [ ! -d "$scratch" ]; then
		graceful_death "cannot find scratch output dir $scratch"
	fi 
	tmpExt=$RANDOM
	tmpdir="$scratch/varscan.$tmpExt"
	mkdir $tmpdir
else
	if [ ! -d "$prevDir" ]; then
		graceful_death "cannot find previous run directory $prevDir"
	fi
	tmpdir=$prevDir
fi
>&2 echo "Output files will be stored in $tmpdir"

# checks if a file exists and has more than one line in it
# several programs in this wrapper will output a single line if they fail
exists(){
  if [ -e "$1" ]
  then
    ct=$(head -n 2 $1 | wc -l | cut -f1 -d' ')
    if [ "$ct" -eq "2" ]; then
        return 0
    else
        return 1
    fi
  else
    return 1
  fi
}

# runOrDie gets its variables directly from MAIN
runOrDie(){
	if exists "$outfile" ; then
		return 0	# nothing to be done
	fi
	for file in $infile; do
		ext=$(echo $file | sed "s/.*\.//");
		[ "$ext" == "bam" ] && continue	# do not check bam files again
		if ! exists "$file" && [ -z $DEBUG ]; then
			graceful_death "cannot run $cmd: missing or corrupted $infile"
		fi
	done
	>&2 echo $cmd
	if [[ -z $DEBUG ]]; then
		date >&2
		eval $cmd
		if ! exists "$outfile" ; then
			graceful_death "failed to find $outfile"
		fi
	fi
}




# correct version of samtools?
cmd="samtools 2>&1 | grep Version | cut -f2 -d' '"
sVersion=$(eval $cmd)
if [ $sVersion != "0.1.18" ]; then
	graceful_death "wrong samtools version: expected 0.1.18, got $sVersion"
fi

# find location of run script so we can get the other necessary scripts
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DNAcopy=$DIR/basicDNAcopy.R
findDelta=$DIR/meanLogRatioByChromosome.py
separateArms=$DIR/separateArms.py
varScan="nice java -Xmx2048m -jar $DIR/VarScan.jar"

########## MAIN ################

# Samtools flagstat
infile="$cBam"
outfile="$tmpdir/control.flagstat"
cmd="samtools flagstat $infile > $outfile"
runOrDie 

infile=$tBam
outfile="$tmpdir/tumor.flagstat"
cmd="samtools flagstat $infile > $outfile"
runOrDie

# Samtools mpileup
infile="$idx $cBam $tBam"
outfile="$tmpdir/mpileup"
cmd="samtools mpileup -q 1 -B -l $white -f $infile > $outfile"
runOrDie


ntest=$(head -n 100000 $tmpdir/mpileup | cut -f3 | grep -c N)
if  [ "$ntest" -eq "100000" ]; then
	graceful_death "it looks like the chromosome names in your bam files don't match the ones in the input genome"
fi

# Varscan copynumber
# must calculate data ratio from flagstat output
# also must move to output dir to run this because varscan doesn't parse the output name
dratio=
if exists $tmpdir/control.flagstat && exists $tmpdir/tumor.flagstat ; then
	cnum=$(grep -m 1 mapped $tmpdir/control.flagstat | cut -f1 -d' ')
	tnum=$(grep -m 1 mapped $tmpdir/tumor.flagstat | cut -f1 -d' ')
	dratio=$(echo "scale=2;$cnum/$tnum" | bc)
fi
if [[ -z $dratio ]] && [ -z $DEBUG ]; then
	graceful_death "could not determine data ratio from $tmpdir/control.flagstat and $tmpdir/tumor.flagstat"
fi 

pushd $tmpdir > /dev/null
vOptions='--min-segment-size 100 --mpileup 1'
dr="--data-ratio $dratio"	# .88 works instead of 0.88
infile="mpileup"
outfile="output.copynumber"
cmd="$varScan copynumber $infile output $vOptions $dr"	# output is base name, copynumber gets added as extension
runOrDie
pushd > /dev/null

# From the output, filter any segments for which the tumor coverage is less than 10
# and the control coverage is less than 20
awk -v x=10 '$6 >= x' $tmpdir/output.copynumber | \
awk -v x=20 '$5 >= x' > $tmpdir/output.copynumber.cov


# Varscan copycaller
infile="$tmpdir/output.copynumber.cov"
outfile="$tmpdir/copyCalled"
ccOptions="--output-file $outfile --output-homdel-file $outfile.homdel"
cmd="$varScan copyCaller $infile $ccOptions"
runOrDie

# Calculate recenter amount
infile="$tmpdir/copyCalled"
delta=$($findDelta $infile)

# Rerun copycaller
infile="$tmpdir/output.copynumber.cov"
outfile="$tmpdir/copyCalled.recenter"
ccOptions="--output-file $outfile --output-homdel-file $outfile.homdel"

cmp=$(awk -v delta=$delta 'END{if (delta < -0.2) {print "lt"} else {if (delta > 0.2) {print "gt"} else {print "eq"}}}' < /dev/null)
if [[ "$cmp" == "lt" ]]; then
    rd=$(echo $delta | sed 's/-//')
    cmd="$varScan copyCaller $infile $ccOptions --recenter-down $rd"
    runOrDie
elif [[ "$cmp" == "gt" ]]; then
    cmd="$varScan copyCaller $infile $ccOptions --recenter-up $delta"
    runOrDie
else
    ln -s copyCalled $tmpdir/copyCalled.recenter
fi

# add p and q to chromosome arms
infile="$tmpdir/copyCalled.recenter"
outfile="$tmpdir/copyCalled.recenter.sep"
cmd="$separateArms $infile $cent > $outfile"
runOrDie

# Circular binary segmentation
infile="$tmpdir/copyCalled.recenter.sep"
outfile="$tmpdir/copyCalled.recenter.sep.SD.2.5.dnacopy.out"
cmd="Rscript $DNAcopy $infile 2.5 >/dev/null"
runOrDie

# remove the arms and print to stdout
sed 's/\.[pq]	/	/' $tmpdir/copyCalled.recenter.sep.SD.2.5.dnacopy.out


